### ISSUE TITLE
Thanks issue

### ISSUE THREAD

**Issue by rjmaris** [george-hawkins/betaengine#2]
Let's say eight years after ... I discovered a never used KL25z Wi-Go kit (the idea came up because of recent purchase of a K64F board).
Without your work I wouldn't be able to establish a wifi login to my AP, since the associated SmartConfig apps are no longer accessible. This also applies to archive.org. Your Java tool made my day... - and for a bit, an NXP community entry helped as well (https://community.nxp.com/t5/Kinetis-Microcontrollers/Freescale-FRDM-KL25Z-Webserver-Example/m-p/251880).

Nice to play with it, and now the stuff is over and I'm going to begin a new project using K64F.
BTW: very interesting to read on your Depletion Region blog how the Smart Config operates by encoding the length of message packets.

**Comment by george-hawkins** [comment]
Thanks for the nice comments. It's been a long time since I thought about SmartConfig.

It's one of those ideas that's technically fun (encoding information in the length of encrypted Wi-Fi packets) but in practice, it's daft and completely insecure - it's amazing it got past any internal review process at TI.

But I'm glad if my work helped you get some mileage out of some fairly ancient dev board :blush:
